# Generated by Django 3.2 on 2020-09-20 09:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0026_auto_20200920_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaladminlevel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
