# Generated by Django 3.2 on 2020-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0027_regionaladminlevel_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='an_crop',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='an_range',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='asap0_id',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='asap_cntry',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='g1_units',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='isocode',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='km2_crop',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='km2_rang2',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='km2_tot',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='name0',
        ),
        migrations.RemoveField(
            model_name='regionaladminlevel',
            name='name0_shr',
        ),
        migrations.AddField(
            model_name='regionaladminlevel',
            name='object_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionaladminlevel',
            name='shape_area',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='regionaladminlevel',
            name='shape_length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
